; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sun Jan 19 2020 01:46:58 GMT-0600 (Central Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


