; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sun Jan 19 2020 01:46:58 GMT-0600 (Central Standard Time)
M280 P0 S10 ; deploy BLTouch

