; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sun Jan 19 2020 01:47:00 GMT-0600 (Central Standard Time)
; Wait for set temperatures to be reached
M116 P1

